### ISSUE TITLE
I encountered a bug in detect

### ISSUE THREAD

**Issue by p110120p1** [itsnine/yolov5-onnxruntime#3]
Hello, when I used the same onnx model to detect the original yolov5 project and this project, I encountered the problem of different results. The original yolov5 project category result is correct, but only part of the category of this project is correct, the recognition box The same, but the confidence level is also different. How to solve this problem?

**Comment by itsnine** [comment]
@p110120p1 sorry for the late answer, I reproduced the problem. I haven't solve this problem yet, because I don't really know the cause of it, probably it could be operations with floating point values in c++, for example, the letterbox function returns visually the same resized image as in python, but the models output for that image is a bit different, even boxes coordinates.

**Comment by p110120p1** [comment]
@itsnine Well, it seems possible that this problem is due to differences in the underlying programming language, and thank you for taking the time to try to fix it

**Comment by itsnine** [comment]
@p110120p1 hi, there were a bug with color conversion, I accidentally used BGR format to detect and I fixed that so in C++ and Python the ONNXRuntime result should be the same now.

**Comment by p110120p1** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by p110120p1** [comment]
@itsnine Okay, that's great. Thanks for taking the bug out of your busy schedule
